version: "3.7"

services:
  api:
    container_name: api_meme
    build:
      context: .
    env_file: .env
    ports:
      - 4200:8080
    command: bash -c "uwsgi --ini config.ini"
    networks: 
      - mainframe

networks: 
  mainframe:
